<?php

namespace app\backend\controller;

use app\common\controller\BaseBackend;
use think\Db;

class System extends BaseBackend
{
    public function _initialize()
    {
        return parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 系统配置
     */
    public function config()
    {
        return $this->fetch();
    }

    /**
     *
     * @return mixed
     */
    public function basicConfig()
    {
        $file = CONF_PATH . 'extra/webinfo.php';
        $config = array_merge(include $file, array_change_key_case($_POST, CASE_UPPER));
        // 以下将一个数组转换成一个字符串
        $str = "<?php\r\n return " . var_export($config, true) . ";\r\n?>";
        if (file_put_contents($file, $str)) {
            return json(['code' => 200, 'msg' => '系统信息修改成功']);
        }
        return json(['code' => 500, 'msg' => '系统信息修改失败']);
    }

    /**
     * 这里如果修改session的配置信息，应该是直接退出登录的
     */
    public function sessionConfig()
    {
        $file = CONF_PATH . 'extra/session.php';
        $config = array_merge(include $file, array_change_key_case($_POST, CASE_LOWER));
        // 以下将一个数组转换成一个字符串
        $str = "<?php\r\n return " . var_export($config, true) . ";\r\n?>";
        if (file_put_contents($file, $str)) {
            return $this->success('Session信息修改成功', "backend/login/login");
        }
        return $this->success('Session信息修改失败');
    }

    /**
     * 开发配置
     * @return mixed
     */
    public function developmentConfig()
    {
        $file = CONF_PATH . 'config.php';
        $develop_config = array_merge(include $file, array_change_key_case($_POST, CASE_LOWER));
        // 以下将一个数组转换成一个字符串
        $str = "<?php\r\n return " . var_export($develop_config, true) . ";\r\n?>";
        if (file_put_contents($file, $str)) {
            return $this->success('环境切换成功');
        }
        return $this->success('环境切换失败');
    }

    /**
     * 邮箱配置
     * @return mixed
     */
    public function emailConfig()
    {
        if (request()->isPost()) {
            $file = CONF_PATH . 'extra/email.php';
            $config = array_merge(include $file, array_change_key_case($_POST, CASE_UPPER));
            // 以下将一个数组转换成一个字符串
            $str = "<?php\r\n return " . var_export($config, true) . ";\r\n?>";
            if (file_put_contents($file, $str)) {
                return $this->success('修改成功');
            }
            return $this->success('修改失败');
        }
    }

    /**
     * @return mixed
     */
    public function wechatConfig()
    {
        $file = CONF_PATH . 'extra/wechat.php';
        $config = array_merge(include $file, array_change_key_case($_POST, CASE_UPPER));
        // 以下将一个数组转换成一个字符串
        $str = "<?php\r\n return " . var_export($config, true) . ";\r\n?>";
        if (file_put_contents($file, $str)) {
            return $this->success('系统信息修改成功');
        }
        return $this->success('系统信息修改失败');
    }

    /**
     * 权限配置
     * @return mixed
     */
    public function authConfig()
    {
        $file = CONF_PATH . 'extra/auth_config.php';
        $config = array_merge(include $file, array_change_key_case($_POST, CASE_LOWER));
        // open_auth 的字符串转化为数组
        $config['open_auth'] = explode(',', $config['open_auth']);
        if (!is_array($config['open_auth'])) {
            return $this->success('系统信息修改失败1');
        }
        // 统一将数组转换成一个字符串
        $str = "<?php\r\n return " . var_export($config, true) . ";\r\n?>";
        if (file_put_contents($file, $str)) {
            return $this->success('系统信息修改成功');
        }
        return $this->success('系统信息修改失败2');
    }

    /**
     * @return mixed
     */
    public function payConfig()
    {
        $this->assign('sub_title', "支付配置");
        return $this->fetch();
    }

    /**
     * 存储配置
     * @return mixed
     */
    public function storageConfig()
    {
        $file = CONF_PATH . 'extra/aliyun_oss.php';
        $config = array_merge(include $file, array_change_key_case($_POST, CASE_UPPER));
        $str = "<?php\r\n return " . var_export($config, true) . ";\r\n?>";
        if (file_put_contents($file, $str)) {
            return $this->success('OSS信息修改成功');
        }
        return $this->success('OSS信息修改失败');
    }

    /**
     * 系统Log
     * @return mixed
     */
    public function actionLog()
    {
        $logs = Db::name("logs")->order('id desc')->paginate(20);
        $this->assign('logs', $logs);
        $this->assign('sub_title', "日志文件");
        return $this->fetch();
    }
}
