<?php

/** .-------------------------------------------------------------------
 * |  Github: https://github.com/Tinywan
 * |  Blog: http://www.cnblogs.com/Tinywan
 * |-------------------------------------------------------------------
 * |  Author: Tinywan(ShaoBo Wan)
 * |  DateTime: 2017/8/28 14:42
 * |  Mail: Overcome.wan@Gmail.com
 * '-------------------------------------------------------------------*/

namespace app\common\controller;

use think\Cache;
use think\Cookie;
use think\Db;
use think\Session;

class BaseFrontendController extends BaseController
{
    protected $uuid;
    protected $member_info;

    /**
     * 初始化用户信息
     */
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        // 用户信息统计,SQL优化：尽量调用field方法显式列出查询的字段
        $userInfo = Db::table('resty_open_user')
            ->where('id', session('open_user_id'))
            ->field('id,account,realname,nickname,admin,avatar,company,address,ip,create_time,type,app_id,app_secret,score')
            ->find();
//        halt($userInfo);
        // 标签统计
        $tags = Db::table('resty_tag')
            ->alias('t')
            ->join('resty_article_tag at', "t.id = at.tag_id")
            ->field('t.name,count(at.article_id) as art_num,at.tag_id')
            ->group('t.id')
            ->cache('RESTY_TAG')
            ->select();
        $tagCounts = Db::table('resty_tag')
            ->cache("RESTY_TAG_COUNTS")
            ->count();

        // 友情链接
        $links = Db::table('resty_link')
            ->order('sort desc')
            ->cache("RESTY_LINK")
            ->select();
        // 分类信息
        $categorys = Db::table('resty_category')
            ->order('id desc')
            ->cache('RESTY_CATEGORY')
            ->select();
        $categoryCounts = Db::table('resty_tag')
            ->cache('RESTY_CATEGORY_COUNT')
            ->count();

        // 导航栏
        $navbars = Db::table('resty_navbar')
            ->where('is_display', 1)
            ->order('sort asc')
            ->cache('RESTY_NAVBAR')
            ->select();

        $this->assign('userInfo', $userInfo);
        $this->assign('links', $links);
        $this->assign('tags', $tags);
        $this->assign('tagCounts', $tagCounts);
        $this->assign('categorys', $categorys);
        $this->assign('categoryCounts', $categoryCounts);
        $this->assign('navbar', $navbars);
    }

    /**
     * Redis缓存DEMO
     */
    public function redisCacheDemo()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        // 用户信息统计
        $userInfo = Db::table('resty_open_user')->where('id', session('open_user_id'))->find();
        // 标签统计
        $tags = Db::table('resty_tag')
            ->alias('t')
            ->join('resty_article_tag at', "t.id = at.tag_id")
            ->field('t.name,count(at.article_id) as art_num,at.tag_id')
            ->group('t.id')
            ->select();
        $tagCacheKey = 'resty_tag';
        if ($this->cache_switch == true && redisCache()->has($tagCacheKey) == true) {
            $tags = redisCache()->get($tagCacheKey);
            $tags[0]['DataSources'] = 'content from Cache';
        } else {
            // 先删除，再查询缓存
            redisCache()->rm($tagCacheKey);
            $tags = Db::table('resty_tag')
                ->alias('t')
                ->join('resty_article_tag at', "t.id = at.tag_id")
                ->field('t.name,count(at.article_id) as art_num,at.tag_id')
                ->group('t.id')
                ->select();
            if ($this->cache_switch == true) redisCache()->set($tagCacheKey, $tags);
            $tags[0]['DataSources'] = 'content from MySQL';
        }

        $tagCountCacheKey = 'resty_tag_count';
        if ($this->cache_switch == true && redisCache()->has($tagCountCacheKey) == true) {
            $tagCounts = redisCache()->get($tagCountCacheKey);
        } else {
            redisCache()->rm($tagCountCacheKey);
            $tagCounts = Db::table('resty_tag')->count();
            if ($this->cache_switch == true) redisCache()->set($tagCountCacheKey, $tagCounts);
        }

        // 文章
        $articleCacheKey = 'resty_article';
        $articles = Db::table('resty_article')->column('id,title,cate_id,image_thumb,content,desc,create_time,author_id,views')->select();
        halt($articles);
        if ($this->cache_switch == true && redisCache()->has($articleCacheKey) == true) {
            $articles = redisCache()->get($articleCacheKey);
            $articles[0]['DataSources'] = 'content from Cache';
        } else {
            // 先删除，再查询缓存
            redisCache()->rm($articleCacheKey);
            $articles = Db::table('resty_article')->order('id desc')->select();
            if ($this->cache_switch == true) redisCache()->set($articleCacheKey, $articles);
            $articles[0]['DataSources'] = 'content from MySQL';
        }

        $articleCountCacheKey = 'resty_article_count';
        if ($this->cache_switch == true && redisCache()->has($articleCountCacheKey) == true) {
            $articleCounts = redisCache()->get($articleCountCacheKey);
        } else {
            redisCache()->rm($articleCountCacheKey);
            $articleCounts = Db::table('resty_article')->count();
            if ($this->cache_switch == true) redisCache()->set($articleCountCacheKey, $articleCounts);
        }

        // 友情链接
        $linkCacheKey = 'resty_link';
        if ($this->cache_switch == true && redisCache()->has($linkCacheKey) == true) {
            $links = redisCache()->get($linkCacheKey);
            $links[0]['DataSources'] = 'content from Cache';
        } else {
            redisCache()->rm($linkCacheKey);
            $links = Db::table('resty_link')->order('sort desc')->select();
            if ($this->cache_switch == true) redisCache()->set($linkCacheKey, $links);
            $links[0]['DataSources'] = 'content from MySQL';
        }

        // 分类信息
        $categoryCacheKey = 'resty_article';
        if ($this->cache_switch == true && redisCache()->has($categoryCacheKey) == true) {
            $categorys = redisCache()->get($categoryCacheKey);
            $categorys[0]['DataSources'] = 'content from Cache';
        } else {
            redisCache()->rm($categoryCacheKey);
            $categorys = Db::table('resty_category')->order('id desc')->select();
            if ($this->cache_switch == true) redisCache()->set($categoryCacheKey, $categorys);
            $categorys[0]['DataSources'] = 'content from MySQL';
        }

        $categoryCountCacheKey = 'resty_category_count';
        if ($this->cache_switch == true && redisCache()->has($categoryCountCacheKey) == true) {
            $categoryCounts = redisCache()->get($categoryCountCacheKey);
        } else {
            redisCache()->rm($categoryCountCacheKey);
            $categoryCounts = Db::table('resty_tag')->count();
            if ($this->cache_switch == true) redisCache()->set($categoryCountCacheKey, $categoryCounts);
        }

        // 导航栏
        $navbarCacheKey = 'resty_navbar';
        if ($this->cache_switch == true && redisCache()->has($navbarCacheKey) == true) {
            $navbars = redisCache()->get($navbarCacheKey);
            $navbars[0]['DataSources'] = 'content from Cache';
        } else {
            redisCache()->rm($navbarCacheKey);
            $navbars = Db::table('resty_navbar')->where('is_display', 1)->order('sort asc')->select();
            if ($this->cache_switch == true) redisCache()->set($navbarCacheKey, $navbars);
            $navbars[0]['DataSources'] = 'content from MySQL';
        }
        $this->assign('userInfo', $userInfo);
        $this->assign('links', $links);
        $this->assign('tags', $tags);
        $this->assign('tagCounts', $tagCounts);
        $this->assign('categorys', $categorys);
        $this->assign('categoryCounts', $categoryCounts);
        $this->assign('articles', $articles);
        $this->assign('articleCounts', $articleCounts);
        $this->assign('navbar', $navbars);
    }


    /**
     * 检测是否登录
     * Power by Mikkle
     * QQ:776329498
     * @return bool
     */
    public function checkLoginGlobal()
    {
        $check_success = false;
        switch ($this->loginType) {
            case 1;
            case "session";
                $this->uuid = Session::get('uuid', 'Global');
                $this->member_info = Session::get('member_info', 'Global');
                if ($this->uuid && $this->member_info) {
                    $check_success = true;
                }
                break;
            case 2;
            case "cache";
                $session_id_check = Cookie::get("session_id");
                $this->uuid = Cache::get("uuid_{$session_id_check}");
                $this->member_info = Cache::get("member_info_{$session_id_check}");
                if ($this->uuid && $this->member_info) {
                    $check_success = true;
                }
                //刷新 缓存有效期
                Cache::set("uuid_{$session_id_check}", $this->uuid);
                Cache::set("member_info_{$session_id_check}", $this->member_info);
                break;
            case 3:
            case "redis":
                break;
            default:
                0;
        }
        return $check_success;
    }

    /**
     * 设置全局登录
     * #User: Mikkle
     * #Email:776329498@qq.com
     * #Date:
     */
    public function setLoginGlobal($member_info = [], $login_code = 0)
    {
        $set_success = false;
        if ($member_info) {
            switch ($this->loginType) {
                case 1:
                case "session":
                    Session::set('member_info', $member_info, 'Global');
                    Session::set('uuid', $member_info['uuid'], 'Global');
                    if ((Session::has("uuid", "Global"))) {
                        $set_success = true;
                    }
                    break;
                case 2:
                case "cache":
                    $session_id = $this->create_uuid("SN");
                    Cookie::set("session_id", $session_id);
                    Cache::set("member_info_$session_id", $member_info);
                    Cache::set("uuid_$session_id", $member_info['uuid']);
                    $session_id_check = Cookie::get("session_id");
                    if ((Cache::get("uuid_{$session_id_check}"))) {
                        $set_success = true;
                    }
                    break;
                case 3:
                case "redis":
                    break;
            }
        }
        if (!$set_success) return false;
        //保存登录记录
        $this->saveLoginInfo($member_info['uuid'], $login_code);
        return true;
    }

    /**
     * 全局退出
     * @return bool
     */
    protected function logoutGlobal()
    {
        switch ($this->loginType) {
            case 1:
            case "session":
                Session::delete('uuid', 'Global');
                Session::delete('member_info', 'Global');
                break;
            case 2:
            case "cache":
                $session_id_check = Cookie::get("session_id");
                Cache::rm("uuid_{$session_id_check}");
                Cache::rm("member_info_{$session_id_check}");
                Cookie::delete("session_id");
                break;
            case 3:
            case "redis":
                break;
        }
        $this->member_info = null;
        $this->uuid = null;
        return true;
    }


}