<?php
/** .-------------------------------------------------------------------
 * |  Github: https://github.com/Tinywan
 * |  Blog: http://www.cnblogs.com/Tinywan
 * |-------------------------------------------------------------------
 * |  Author: Tinywan(ShaoBo Wan)
 * |  DateTime: 2017/10/6 22:23
 * |  Mail: Overcome.wan@Gmail.com
 * |  Created by PhpStorm
 * '-------------------------------------------------------------------*/

namespace app\frontend\controller;


use app\common\controller\BaseFrontend;
use think\Db;

class Live extends BaseFrontend
{
    protected $db;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db = new \app\common\model\Live();
    }

    public function index()
    {
        $id = input('param.id');
        $live = Db::table('resty_live')->where('id',$id)->find();
        $this->assign('live',$live);
        return $this->fetch();
    }
}