<?php
/**
 * Created by PhpStorm.
 * User: tinywan
 * Date: 2017/7/1
 * Time: 13:40
 */

namespace app\frontend\controller;

use app\common\model\OpenUser;
use think\Controller;
use think\Db;
use think\Log;
use think\Request;

class Member extends Controller
{
    protected $open_user_db;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->open_user_db = new OpenUser();
    }

    public function sendEmail()
    {
        $str = <<<html
            您好！<p></p>
            感谢您在Tinywan世界注册帐户！<p></p>
			帐户需要激活才能使用，赶紧激活成为Tinywan家园的正式一员吧:)<p></p>
            点击下面的链接立即激活帐户(或将网址复制到浏览器中打开):<p></p>
html;
        $data["str"] = $str;
        $result = send_email('756684177@qq.com', '物联网智能数据 帐户激活邮件--', $str);
        halt($result);
    }

    public function index()
    {
        return $this->fetch();
    }

    public function login()
    {
        return $this->fetch();
    }

    /**
     * 邮箱注册
     * @param $data
     * @return array
     */
    public function emailRegister($data)
    {
        // 2 检测邮箱是否被注册
        $time = time();
        $passwordToken = md5($data['email'] . md5($data['password']) . $time); //创建用于激活识别码
         $userInfo = Db::table('resty_open_user')->where('email', $data['email'])->find();
        if ($userInfo) return ['valid' => 0, 'msg' => "该邮箱已经被注册"];
        // 3 插入数据库
        $insertData = [
            'account' => 'Tinywan'.rand(1111,9999),
            'password' => md5($data["password"]),
            'email' => $data["email"],
            'password_token' => $passwordToken,
            'ip' => "127.0.0.1",
        ];
        $userId = Db::table('resty_open_user')->insertGetId($insertData);
        if (!$userId) return ['valid' => 0, 'msg' => "数据库添加数据失败"];
        // session 记录
        session('open_user_id', $userId);
        session('open_user_username', $insertData['account']);
        // 4 发送邮件
        $emailSendDomain = $_SERVER["HTTP_HOST"];
        $checkstr = base64_encode($data['email']);
        $auth_key = get_auth_key($data['email']);
        $link = "http://{$emailSendDomain}/frontend/member/emailRegisterUrlValid?checkstr=$checkstr&auth_key={$auth_key}";
        $str = <<<html
            您好！<p></p>
            感谢您在Tinywan世界注册帐户！<p></p>
			帐户需要激活才能使用，赶紧激活成为Tinywan家园的正式一员吧:)<p></p>
            点击下面的链接立即激活帐户(或将网址复制到浏览器中打开):<p></p>
			$link
html;
        $data["str"] = $str;
        $result = send_email($data["email"], '物联网智能数据 帐户激活邮件--', $str);
        if ($result['error'] == 1) return ['valid' => 0, 'msg' => "邮件发送失败，请联系管理员"];
        return ['valid' => 1, 'msg' => $data['email'] . "注册成功，请立即验证邮箱<br/>邮件发送至: " . $data['email']];
    }

    /**
     * 注册
     * @return mixed
     */
    public function signup()
    {
        //1 验证数据
        if ($this->request->isPost()) {
            $res = $this->emailRegister(input("post."));
            if ($res['valid']) {
                //success
                add_operation_log('登录成功');
                $this->success($res['msg'], "frontend/index/index");
                exit;
            } else {
                //fail
                add_operation_log('登录失败');
                $this->error($res['msg']);
                exit;
            }
        }
        return $this->fetch();
    }

    /**
     * 邮箱注册URL验证
     * @param Request $request
     */
    public function emailRegisterUrlValid(Request $request)
    {
        if ($request->isGet()) {
            $res = (new Admin())->emailRegisterUrlValid(input("get."), "frontend");
            if ($res["valid"]) {
                //success 把目前的邮箱地址保存在session中
                $this->success($res['msg'], "frontend/index/index");
            } else {
                $this->error($res['msg'], "frontend/index/login");
            }
        }
    }

    /**
     * 登录
     * @return mixed
     */
    public function signin()
    {
        return $this->fetch();
    }

    /**
     *  ---------------------------------------------------------------------------------手机注册
     *  http://www.tinywan_thinkphp5.com/frontend/member/mobileSignUp
     * @return mixed
     */
    public function mobileSignUp(Request $request)
    {
        //1 验证数据
        if ($request->isPost()) {
            $res = (new Admin())->mobileRegister(input("post."));
            if ($res['valid']) {
                //success
                add_operation_log('注册成功');
                $this->success($res['msg'], "frontend/index/index");
                exit;
            } else {
                //fail
                add_operation_log('登录失败');
                $this->error($res['msg']);
                exit;
            }
        }
        return $this->fetch();
    }

    /**
     * 手机验证码
     * @return mixed
     */
    public function mobileCodeCheck(Request $request)
    {
        $mobile = $request->get("mobile");
        //判断该手机是否被注册
        $userInfo = Db::table("resty_user")->where("mobile", $mobile)->find();
        if ($userInfo) {
            $this->error("该手机号已经存在");
            exit;
        }
        // 验证码
        $code = rand(100000, 999999);
        // 过期时间
        $expireTime = 60;
        //保存当前手机的验证码到Redis
        session("TINYWAN:" . $mobile, $code);
        //发送验证码操作
        $sendRes = send_dayu_sms($mobile, "register", ['code' => $code]);
        //发送成功
        if (isset($sendRes->result->success) && ($sendRes->result->success == true)) {
            $res = [
                "code" => 200,
                "msg" => "验证码发送成功"
            ];
            Log::info("--------------------验证码 : " . $mobile . " 发送成功");
        } else {
            $res = [
                "code" => 500,
                "msg" => "验证码发送失败"
            ];
            Log::error("-------------------验证码 : " . $mobile . " 发送失败 ，错误原因：" . $sendRes->sub_msg);
        }
        return json($res);
    }

    /**
     * -------------------------------------------------------------------------------个人中心
     */
    public function dd(){

    }

    public function getCode()
    {
        $data = [
            'username' => "11111111",
            'password' => md5("1111111111111111111"),
            'mobile' => 13669361192,
            'loginip' => "127.0.0.1",
        ];
        $res = Db::table("resty_user")->insertGetId($data);
        halt($res);
        //1 验证数据
        halt(session("TINYWAN:13669361192"));
    }

}